### ISSUE TITLE
Remove the like button

### ISSUE THREAD

**Issue by hschaeidt** [Letscodeit/gitmostwanted.com#10]
As we have already the Stars amount from github.

**Comment by kkamkou** [comment]
@hschaeidt I'm thinking about is that the like button helps me somehow. Usually I find more or less interesting repos. Later, useless. Mb, we've removed the like button very fast? I don't want to star/watch them, because they are not interesting right now, but I feel like they might be very useful in the future. What do u think?

**Comment by kkamkou** [comment]
@hschaeidt ?

**Comment by hschaeidt** [comment]
Well I think we are still experimenting a lot. We didn't really test the
feature yet. So I'm okay with reverting the issue.

But after what you described you are looking forward some kind of
"bookmark" button. Let's collect the data and see how we can analyze it for
making potential suggestions.

Am Mittwoch, 20. Mai 2015 schrieb Kanstantsin Kamkou :

**Comment by kkamkou** [comment]
k, got it. let us try

**Comment by hschaeidt** [comment]
Maybe we can use it to find interesting people instead of repos
